from django.db import models

# Create your models here.
class seller_singup(models.Model):
    Name =          models.CharField(max_length=50)
    Mobile_number=  models.CharField(max_length=15)
    Email=          models.CharField(max_length=50,primary_key=True)
    password =      models.CharField(max_length=50)
    main_id =       models.CharField(max_length=20)
    Type =          models.CharField(max_length=20,default="Seller")
    product_count=  models.CharField(max_length=20,default='0')

class clothes(models.Model):
    name =          models.CharField(max_length=100)
    price =         models.CharField(max_length=10,null=True)
    description =   models.CharField(max_length=1000,blank=True, null=True)
    product_id =    models.CharField(max_length=100, unique=True)
    product_img =   models.CharField(max_length=1000 ,blank=True, null=True)
    seller_id =     models.CharField(max_length=100)
    option =        models.CharField(max_length=50)
    color =         models.CharField(max_length=50, blank=True, null=True)
    brand =         models.CharField(max_length=100, blank=True, null=True)
    size =          models.CharField(max_length=50, blank=True, null=True)
    fabric =        models.CharField(max_length=100, blank=True, null=True)
    design =        models.CharField(max_length=100, blank=True, null=True)
    patterns =      models.CharField(max_length=100, blank=True, null=True)
    type =          models.CharField(max_length=50, blank=True, null=True)
    model =         models.CharField(max_length=100, blank=True, null=True)
    user =          models.CharField(max_length=50, blank=True, null=True)
    weight =        models.CharField(max_length=10, blank=True, null=True)

class shoes(models.Model):
    name =          models.CharField(max_length=100)
    price =         models.CharField(max_length=10)
    description =   models.CharField(max_length=1000,blank=True, null=True)
    product_id =    models.CharField(max_length=100, unique=True)
    product_img =   models.CharField(max_length=10000)
    seller_id =     models.CharField(max_length=100)
    option =        models.CharField(max_length=50)
    color =         models.CharField(max_length=50)
    brand =         models.CharField(max_length=100)
    size =          models.CharField(max_length=50)
    fabric =        models.CharField(max_length=100)
    design =        models.CharField(max_length=100)
    patterns =      models.CharField(max_length=100)
    type =          models.CharField(max_length=50)
    model =         models.CharField(max_length=100)
    user =          models.CharField(max_length=50)
    weight =        models.CharField(max_length=10)

class Mobile(models.Model):
    name =          models.CharField(max_length=100)
    price =         models.CharField(max_length = 10)
    description =   models.CharField(max_length = 1000)
    product_id =    models.CharField(max_length=100, unique=True)
    product_img =   models.CharField(max_length = 1000)
    seller_id =     models.CharField(max_length=100)
    option =        models.CharField(max_length=50)
    display_size =  models.CharField(max_length=50,null=True)
    display =       models.CharField(max_length=100)
    battery =       models.CharField(max_length=100)
    network =       models.CharField(max_length=100)
    brand =         models.CharField(max_length=100)
    ram_rom =       models.CharField(max_length=100)
    weight =        models.CharField(max_length = 10)
    camera =        models.CharField(max_length=100)
    processors =    models.CharField(max_length=100)
    warranty =      models.CharField(max_length=100)
    model_number =  models.CharField(max_length=100)
    color =         models.CharField(max_length=50)
    sim_slot =      models.CharField(max_length=50)
    wifi =          models.CharField(max_length=100)
    battery_type =  models.CharField(max_length=100)
    graphics =      models.CharField(max_length=100)
    charging =      models.CharField(max_length=100)

class Laptop(models.Model):
    name =          models.CharField(max_length=100)
    price =         models.CharField(max_length = 10)
    description =   models.CharField(max_length = 1000)
    product_id =    models.CharField(max_length = 10)
    product_img =   models.CharField(max_length = 1000)
    seller_id =     models.CharField(max_length=100)
    option =        models.CharField(max_length=50)
    
    display_size =  models.CharField(max_length=50)
    display =       models.CharField(max_length=100)
    battery =       models.CharField(max_length=100)
    network =       models.CharField(max_length=100)
    brand =         models.CharField(max_length=100)
    ram_rom =       models.CharField(max_length=100)
    weight =        models.CharField(max_length = 10)
    camera =        models.CharField(max_length=100)
    processors =    models.CharField(max_length=100)
    warranty =      models.CharField(max_length=100)
    model_number =  models.CharField(max_length=100)
    color =         models.CharField(max_length=50)
    sim_slot =      models.CharField(max_length=50)
    wifi =          models.CharField(max_length=100)
    battery_type =  models.CharField(max_length=100)
    graphics =      models.CharField(max_length=100)
    charging =      models.CharField(max_length=100)

class Gadget(models.Model):
    name =          models.CharField(max_length=100)
    price =         models.CharField(max_length = 1000)
    description =   models.CharField(max_length = 1000)
    product_id =    models.CharField(max_length=100, unique=True)
    seller_id =     models.CharField(max_length=100)
    product_img =   models.CharField(max_length = 1000)
    option =        models.CharField(max_length=50)
    battery_present = models.CharField(max_length = 1000)
    chargeable =    models.CharField(max_length = 1000)
    brand =         models.CharField(max_length=100)
    weight =        models.CharField(max_length = 1000)
    model_number =  models.CharField(max_length=100)
    color =         models.CharField(max_length=50)
    wireless_connection = models.CharField(max_length=100)
    battery_type =  models.CharField(max_length=100)

class Toy(models.Model):
    name =          models.CharField(max_length=100)
    price =         models.CharField(max_length=10,null=True)
    description =   models.CharField(max_length=1000,blank=True, null=True)
    product_id =    models.CharField(max_length=100, unique=True)
    product_img =   models.CharField(max_length=1000 ,blank=True, null=True)
    seller_id =     models.CharField(max_length=100)
    option =        models.CharField(max_length=50)
    age =           models.CharField(max_length = 10,blank=True, null=True)
    weight =        models.CharField(max_length=10,blank=True, null=True)
    chargeable =    models.CharField(max_length=10,blank=True, null=True)
    size =          models.CharField(max_length=50,blank=True, null=True)
    material =      models.CharField(max_length=100,blank=True, null=True)
    brand =         models.CharField(max_length=100,blank=True, null=True)
    type =          models.CharField(max_length=50,blank=True, null=True)
    model =         models.CharField(max_length=100,blank=True, null=True)
    user =          models.CharField(max_length=50,blank=True, null=True)

class all_product(models.Model):
    name =          models.CharField(max_length=100)
    price =         models.CharField(max_length=10,blank=True, null=True)
    description =   models.CharField(max_length=1000, blank=True, null=True)
    product_id =    models.CharField(max_length=100, unique=True)
    product_img =   models.CharField(max_length=1000, blank=True, null=True)
    seller_id =     models.CharField(max_length=100)
    option =        models.CharField(max_length=50)
    color =         models.CharField(max_length=50, blank=True, null=True)
    brand =         models.CharField(max_length=100, blank=True, null=True)
    weight =        models.CharField(max_length=10, blank=True, null=True)

    # Clothes-specific fields
    size =          models.CharField(max_length=50, blank=True, null=True)
    fabric =        models.CharField(max_length=100, blank=True, null=True)
    design =        models.CharField(max_length=100, blank=True, null=True)
    patterns =      models.CharField(max_length=100, blank=True, null=True)
    type =          models.CharField(max_length=50, blank=True, null=True)
    model =         models.CharField(max_length=100, blank=True, null=True)
    user =          models.CharField(max_length=50, blank=True, null=True)

    # Shoes-specific fields
    # (all shoes-specific fields are covered by common fields)

    # Mobile-specific fields
    display_size =  models.CharField(max_length=50, blank=True, null=True)
    display =       models.CharField(max_length=100, blank=True, null=True)
    battery =       models.CharField(max_length=100, blank=True, null=True)
    network =       models.CharField(max_length=100, blank=True, null=True)
    ram_rom =       models.CharField(max_length=100, blank=True, null=True)
    camera =        models.CharField(max_length=100, blank=True, null=True)
    processors =    models.CharField(max_length=100, blank=True, null=True)
    warranty =      models.CharField(max_length=100, blank=True, null=True)
    model_number =  models.CharField(max_length=100, blank=True, null=True)
    sim_slot =      models.CharField(max_length=50, blank=True, null=True)
    wifi =          models.CharField(max_length=100, blank=True, null=True)
    battery_type =  models.CharField(max_length=100, blank=True, null=True)
    graphics =      models.CharField(max_length=100, blank=True, null=True)
    charging =      models.CharField(max_length=100, blank=True, null=True)

    # Laptop-specific fields
    # (all laptop-specific fields are covered by mobile fields)

    # Gadget-specific fields
    battery_present = models.CharField(max_length=1000, blank=True, null=True)
    chargeable =    models.CharField(max_length=1000, blank=True, null=True)
    wireless_connection = models.CharField(max_length=100, blank=True, null=True)

    # Toy-specific fields
    age =           models.CharField(max_length=10, blank=True, null=True)
    size =          models.CharField(max_length=50, blank=True, null=True)
    material =      models.CharField(max_length=100, blank=True, null=True)
    chargeable =    models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return self.name

