# Generated by Django 5.0.6 on 2024-07-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_user_email_user_singup_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_singup',
            name='Type',
            field=models.CharField(default='Customer', max_length=20),
        ),
    ]
