# Generated by Django 5.0.6 on 2024-07-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_addshoppingaddres_delete_shoppingaddres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addshoppingaddres',
            name='customerId',
            field=models.CharField(max_length=30),
        ),
    ]
