# Generated by Django 5.0.6 on 2024-07-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_addshoppingaddres_recivermobileno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addshoppingaddres',
            name='Home_Rode_Address',
            field=models.CharField(max_length=50),
        ),
    ]
