# Generated by Django 5.0.6 on 2024-07-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_addshoppingaddres_home_rode_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addshoppingaddres',
            name='ReciverMobileNo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='addshoppingaddres',
            name='ReciverName',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='addshoppingaddres',
            name='city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='addshoppingaddres',
            name='customerId',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='addshoppingaddres',
            name='pincode',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='addshoppingaddres',
            name='state',
            field=models.CharField(max_length=150),
        ),
    ]
