# Generated by Django 5.0.6 on 2024-07-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_addshoppingaddres_recivermobileno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addshoppingaddres',
            name='customerId',
            field=models.CharField(max_length=50),
        ),
    ]
