# Generated by Django 5.0.6 on 2024-07-07 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_singup',
            old_name='user_email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='user_singup',
            old_name='user_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='user_singup',
            old_name='user_id',
            new_name='main_id',
        ),
        migrations.RenameField(
            model_name='user_singup',
            old_name='user_password',
            new_name='password',
        ),
    ]
