# Generated by Django 5.0.6 on 2024-07-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_shopping'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shopping',
            new_name='shoppingAddres',
        ),
    ]
