# Generated by Django 5.0.6 on 2024-07-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_rename_shopping_shoppingaddres'),
    ]

    operations = [
        migrations.CreateModel(
            name='addShoppingAddres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.CharField(max_length=50)),
                ('ReciverName', models.CharField(max_length=50)),
                ('ReciverMobileNo', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=10)),
                ('Home_Rode_Address', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='shoppingAddres',
        ),
    ]
