# Generated by Django 5.0.6 on 2024-07-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_addshoppingaddres_recivername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addshoppingaddres',
            name='ReciverName',
            field=models.CharField(max_length=20),
        ),
    ]
