# Generated by Django 5.0.6 on 2024-07-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_addshoppingaddres_home_rode_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addshoppingaddres',
            name='Home_Rode_Address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='addshoppingaddres',
            name='ReciverMobileNo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='addshoppingaddres',
            name='ReciverName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='addshoppingaddres',
            name='pincode',
            field=models.CharField(max_length=20),
        ),
    ]
