# Generated by Django 5.0.6 on 2024-07-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_addshoppingaddres_customerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingAddres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.CharField(max_length=50)),
                ('ReciverName', models.CharField(max_length=60)),
                ('ReciverMobileNo', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('Home_Rode_Address', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='addShoppingAddres',
        ),
    ]
