# Generated by Django 5.0.6 on 2024-07-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seller_singup',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Mobile_number', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('main_id', models.CharField(max_length=20)),
            ],
        ),
    ]
