# Generated by Django 5.0.6 on 2024-07-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_singup',
            name='Type',
            field=models.CharField(default='Seller', max_length=20),
        ),
        migrations.AddField(
            model_name='seller_singup',
            name='product_count',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
