# Generated by Django 5.0.6 on 2024-07-08 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_clothes_gadget_laptop_mobile_seller_shoes_toy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='product_count',
        ),
        migrations.RemoveField(
            model_name='gadget',
            name='product_count',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='product_count',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='product_count',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='product_count',
        ),
        migrations.RemoveField(
            model_name='toy',
            name='product_count',
        ),
    ]
