# Generated by Django 5.0.6 on 2024-07-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0005_alter_clothes_brand_alter_clothes_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.AlterField(
            model_name='clothes',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='product_img',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='product_img',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='weight',
            field=models.CharField(max_length=10),
        ),
    ]
