# Generated by Django 5.0.6 on 2024-07-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0008_alter_mobile_display_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('product_img', models.CharField(blank=True, max_length=1000, null=True)),
                ('seller_id', models.CharField(max_length=100)),
                ('option', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('fabric', models.CharField(blank=True, max_length=100, null=True)),
                ('design', models.CharField(blank=True, max_length=100, null=True)),
                ('patterns', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('display_size', models.CharField(blank=True, max_length=50, null=True)),
                ('display', models.CharField(blank=True, max_length=100, null=True)),
                ('battery', models.CharField(blank=True, max_length=100, null=True)),
                ('network', models.CharField(blank=True, max_length=100, null=True)),
                ('ram_rom', models.CharField(blank=True, max_length=100, null=True)),
                ('camera', models.CharField(blank=True, max_length=100, null=True)),
                ('processors', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty', models.CharField(blank=True, max_length=100, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sim_slot', models.CharField(blank=True, max_length=50, null=True)),
                ('wifi', models.CharField(blank=True, max_length=100, null=True)),
                ('battery_type', models.CharField(blank=True, max_length=100, null=True)),
                ('graphics', models.CharField(blank=True, max_length=100, null=True)),
                ('charging', models.CharField(blank=True, max_length=100, null=True)),
                ('battery_present', models.CharField(blank=True, max_length=1000, null=True)),
                ('wireless_connection', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('chargeable', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
