# Generated by Django 5.0.6 on 2024-07-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0010_alter_toy_age_alter_toy_brand_alter_toy_chargeable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_product',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
