# Generated by Django 5.0.6 on 2024-07-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_id', models.CharField(max_length=20)),
                ('cartCount', models.CharField(max_length=10)),
                ('productId', models.CharField(max_length=20)),
                ('Time', models.CharField(max_length=30)),
            ],
        ),
    ]
