# Generated by Django 5.0.6 on 2024-07-11 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='main_id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='cartCount',
            new_name='quentity',
        ),
    ]
